services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: ${REDIS_HOST}
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli","-p", "${REDIS_PORT}","ping"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - sharetube

  fluent-bit:
    image: fluent/fluent-bit:3.2.3
    container_name: sharetube-fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - logs:/logs:ro
    depends_on:
      - loki
    networks:
    - sharetube

  loki:
    image: grafana/loki:3.3.2
    container_name: sharetube-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
    - sharetube

  grafana:
    image: grafana/grafana:11.4.0
    container_name: sharetube-grafana
    depends_on:
      - fluent-bit
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
    - sharetube

  server:
    image: sharetube-server:latest
    container_name: sharetube-server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    depends_on:
      - redis
      - fluent-bit
    volumes:
      - logs:/var/log
    networks:
      - sharetube

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sharetube

volumes:
  grafana:
  logs:

networks:
  sharetube:
    driver: bridge