services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: ${REDIS_HOST}
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - sharetube

  server:
    image: sharetube-server-dev:latest # use local image
    # image: sharetube/server:latest
    container_name: sharetube-server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - redis
    stop_grace_period: 30s
    networks:
      - sharetube

  nginx:
    image: nginx:1.27-alpine
    container_name: sharetube-nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"
    networks:
      - sharetube

networks:
  sharetube:
    driver: bridge
